version: '3.1'

volumes:
  wp_data:
services:
  nginx:
    build: ./requirements/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/conf.d/default.conf
  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wp_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=sbars
      - WORDPRESS_DB_PASSWORD=password123
      - WORDPRESS_DB_NAME=wordpress
