version: '3.8'

volumes:
  wp_data:
    driver: /Users/sbars/data/wordpress
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/sbars/data/wordpress'
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/sbars/data/mariadb'

networks:
  inception:
    driver: bridge

services:
  nginx:
    build: ./requirements/nginx
    env_file: .env
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - wp_data:/var/www/wordpress
    depends_on:
      - wordpress
    restart: always
  wordpress:
    build: ./requirements/wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    expose:
      - "9000"
    restart: always
  mariadb:
    build: ./requirements/mariadb
    env_file: .env
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always