version: '3.1'

networks:
    inception:

volumes:
  wp_data:
  mariadb_data:
services:
  nginx:
    build: ./requirements/nginx
    env_file: .env
    ports:
      - 8080:80
      - 443:443
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always
  wordpress:
    build: ./requirements/wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    expose:
      - "9000"
    restart: always
  mariadb:
    build: ./requirements/mariadb
    env_file: .env
    # ports:
    #   - "3306:3306"
    #   - "80:80"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    # restart: always
