version: '3.1'

networks:
    inception:
      driver: bridge

volumes:
  wp_data:
    driver: local # ici nous stockons le volume en local
    driver_opts:
      type: 'none' 									# aucun type spécifique
      o: 'bind'
      device: '/Users/sbars/data/wordpress' 		#Ou stocker le dossier sur votre ordinateur en local
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'										 # Les Bind Mounts sont des volumes qui se montent sur un chemin d'accès à l'hôte, et ils peuvent être modifiés par d'autres processus en dehors de docker.
      device: '/Users/sbars/data/mariadb'			#Ou stocker le dossier sur votre ordinateur en local

services:
  nginx:
    build: ./requirements/nginx
    env_file: .env
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - wp_data:/var/www/wordpress
    depends_on:
      - wordpress
    restart: always
  wordpress:
    build: ./requirements/wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    expose:
      - "9000"
    restart: always
  mariadb:
    build: ./requirements/mariadb
    env_file: .env
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
