version: '3.9'

networks:
  inception:
    driver: bridge

volumes:
  wp:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/sbars/data/wordpress'
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/sbars/data/mariadb'

services:
  mariadb:
    container_name: mariadb
    networks:
    - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
    - db:/var/lib/mysql
    - wp:/var/www/wordpress
    expose:
    - "3306"
    restart: unless-stopped
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    volumes:
    - wp:/var/www/wordpress
    networks:
    - inception
    depends_on:
    - wordpress
    env_file: .env
    ports:
    - 443:443
    restart: on-failure
  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
    - wp:/var/www/wordpress
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
    - mariadb
    restart: on-failure
    expose:
      - "9000"
